// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_status_string
std::string cpp_status_string(int status);
RcppExport SEXP _rtranscribe_cpp_status_string(SEXP statusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type status(statusSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_status_string(status));
    return rcpp_result_gen;
END_RCPP
}
// cpp_log_set
void cpp_log_set(bool enabled, int max_rank);
RcppExport SEXP _rtranscribe_cpp_log_set(SEXP enabledSEXP, SEXP max_rankSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type enabled(enabledSEXP);
    Rcpp::traits::input_parameter< int >::type max_rank(max_rankSEXP);
    cpp_log_set(enabled, max_rank);
    return R_NilValue;
END_RCPP
}
// cpp_log_drain
List cpp_log_drain();
RcppExport SEXP _rtranscribe_cpp_log_drain() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_log_drain());
    return rcpp_result_gen;
END_RCPP
}
// cpp_version
List cpp_version();
RcppExport SEXP _rtranscribe_cpp_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_version());
    return rcpp_result_gen;
END_RCPP
}
// cpp_init_backends_default
int cpp_init_backends_default();
RcppExport SEXP _rtranscribe_cpp_init_backends_default() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_init_backends_default());
    return rcpp_result_gen;
END_RCPP
}
// cpp_init_backends
int cpp_init_backends(std::string dir);
RcppExport SEXP _rtranscribe_cpp_init_backends(SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type dir(dirSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_init_backends(dir));
    return rcpp_result_gen;
END_RCPP
}
// cpp_backend_available
bool cpp_backend_available(std::string kind);
RcppExport SEXP _rtranscribe_cpp_backend_available(SEXP kindSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type kind(kindSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_backend_available(kind));
    return rcpp_result_gen;
END_RCPP
}
// cpp_devices
List cpp_devices();
RcppExport SEXP _rtranscribe_cpp_devices() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_devices());
    return rcpp_result_gen;
END_RCPP
}
// cpp_model_load
SEXP cpp_model_load(std::string path, std::string backend, int gpu_device);
RcppExport SEXP _rtranscribe_cpp_model_load(SEXP pathSEXP, SEXP backendSEXP, SEXP gpu_deviceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type gpu_device(gpu_deviceSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_model_load(path, backend, gpu_device));
    return rcpp_result_gen;
END_RCPP
}
// cpp_model_capabilities
List cpp_model_capabilities(SEXP model);
RcppExport SEXP _rtranscribe_cpp_model_capabilities(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_model_capabilities(model));
    return rcpp_result_gen;
END_RCPP
}
// cpp_model_supports
bool cpp_model_supports(SEXP model, std::string feature);
RcppExport SEXP _rtranscribe_cpp_model_supports(SEXP modelSEXP, SEXP featureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< std::string >::type feature(featureSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_model_supports(model, feature));
    return rcpp_result_gen;
END_RCPP
}
// cpp_model_info
List cpp_model_info(SEXP model);
RcppExport SEXP _rtranscribe_cpp_model_info(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_model_info(model));
    return rcpp_result_gen;
END_RCPP
}
// cpp_model_meta
SEXP cpp_model_meta(SEXP model, std::string key);
RcppExport SEXP _rtranscribe_cpp_model_meta(SEXP modelSEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< std::string >::type key(keySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_model_meta(model, key));
    return rcpp_result_gen;
END_RCPP
}
// cpp_model_device
SEXP cpp_model_device(SEXP model);
RcppExport SEXP _rtranscribe_cpp_model_device(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_model_device(model));
    return rcpp_result_gen;
END_RCPP
}
// cpp_model_accepts_ext_kind
bool cpp_model_accepts_ext_kind(SEXP model, std::string slot, std::string kind);
RcppExport SEXP _rtranscribe_cpp_model_accepts_ext_kind(SEXP modelSEXP, SEXP slotSEXP, SEXP kindSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< std::string >::type slot(slotSEXP);
    Rcpp::traits::input_parameter< std::string >::type kind(kindSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_model_accepts_ext_kind(model, slot, kind));
    return rcpp_result_gen;
END_RCPP
}
// cpp_tokenize
IntegerVector cpp_tokenize(SEXP model, std::string text);
RcppExport SEXP _rtranscribe_cpp_tokenize(SEXP modelSEXP, SEXP textSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< std::string >::type text(textSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_tokenize(model, text));
    return rcpp_result_gen;
END_RCPP
}
// cpp_session_init
SEXP cpp_session_init(SEXP model, int n_threads, std::string kv_type, int n_ctx);
RcppExport SEXP _rtranscribe_cpp_session_init(SEXP modelSEXP, SEXP n_threadsSEXP, SEXP kv_typeSEXP, SEXP n_ctxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< std::string >::type kv_type(kv_typeSEXP);
    Rcpp::traits::input_parameter< int >::type n_ctx(n_ctxSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_session_init(model, n_threads, kv_type, n_ctx));
    return rcpp_result_gen;
END_RCPP
}
// cpp_open
SEXP cpp_open(std::string path, std::string backend, int gpu_device, int n_threads, std::string kv_type, int n_ctx);
RcppExport SEXP _rtranscribe_cpp_open(SEXP pathSEXP, SEXP backendSEXP, SEXP gpu_deviceSEXP, SEXP n_threadsSEXP, SEXP kv_typeSEXP, SEXP n_ctxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type gpu_device(gpu_deviceSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< std::string >::type kv_type(kv_typeSEXP);
    Rcpp::traits::input_parameter< int >::type n_ctx(n_ctxSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_open(path, backend, gpu_device, n_threads, kv_type, n_ctx));
    return rcpp_result_gen;
END_RCPP
}
// cpp_session_limits
List cpp_session_limits(SEXP session);
RcppExport SEXP _rtranscribe_cpp_session_limits(SEXP sessionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_session_limits(session));
    return rcpp_result_gen;
END_RCPP
}
// cpp_session_model
SEXP cpp_session_model(SEXP session);
RcppExport SEXP _rtranscribe_cpp_session_model(SEXP sessionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_session_model(session));
    return rcpp_result_gen;
END_RCPP
}
// cpp_run
List cpp_run(SEXP session, NumericVector pcm, List opts, bool interruptible);
RcppExport SEXP _rtranscribe_cpp_run(SEXP sessionSEXP, SEXP pcmSEXP, SEXP optsSEXP, SEXP interruptibleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pcm(pcmSEXP);
    Rcpp::traits::input_parameter< List >::type opts(optsSEXP);
    Rcpp::traits::input_parameter< bool >::type interruptible(interruptibleSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_run(session, pcm, opts, interruptible));
    return rcpp_result_gen;
END_RCPP
}
// cpp_run_batch
List cpp_run_batch(SEXP session, List pcms, List opts, bool interruptible);
RcppExport SEXP _rtranscribe_cpp_run_batch(SEXP sessionSEXP, SEXP pcmsSEXP, SEXP optsSEXP, SEXP interruptibleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    Rcpp::traits::input_parameter< List >::type pcms(pcmsSEXP);
    Rcpp::traits::input_parameter< List >::type opts(optsSEXP);
    Rcpp::traits::input_parameter< bool >::type interruptible(interruptibleSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_run_batch(session, pcms, opts, interruptible));
    return rcpp_result_gen;
END_RCPP
}
// cpp_stream_begin
void cpp_stream_begin(SEXP session, List run_opts, List stream_opts);
RcppExport SEXP _rtranscribe_cpp_stream_begin(SEXP sessionSEXP, SEXP run_optsSEXP, SEXP stream_optsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    Rcpp::traits::input_parameter< List >::type run_opts(run_optsSEXP);
    Rcpp::traits::input_parameter< List >::type stream_opts(stream_optsSEXP);
    cpp_stream_begin(session, run_opts, stream_opts);
    return R_NilValue;
END_RCPP
}
// cpp_stream_feed
List cpp_stream_feed(SEXP session, NumericVector pcm, bool interruptible);
RcppExport SEXP _rtranscribe_cpp_stream_feed(SEXP sessionSEXP, SEXP pcmSEXP, SEXP interruptibleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pcm(pcmSEXP);
    Rcpp::traits::input_parameter< bool >::type interruptible(interruptibleSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_stream_feed(session, pcm, interruptible));
    return rcpp_result_gen;
END_RCPP
}
// cpp_stream_finalize
List cpp_stream_finalize(SEXP session, bool interruptible);
RcppExport SEXP _rtranscribe_cpp_stream_finalize(SEXP sessionSEXP, SEXP interruptibleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    Rcpp::traits::input_parameter< bool >::type interruptible(interruptibleSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_stream_finalize(session, interruptible));
    return rcpp_result_gen;
END_RCPP
}
// cpp_stream_reset
void cpp_stream_reset(SEXP session);
RcppExport SEXP _rtranscribe_cpp_stream_reset(SEXP sessionSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    cpp_stream_reset(session);
    return R_NilValue;
END_RCPP
}
// cpp_stream_text
List cpp_stream_text(SEXP session);
RcppExport SEXP _rtranscribe_cpp_stream_text(SEXP sessionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_stream_text(session));
    return rcpp_result_gen;
END_RCPP
}
// cpp_stream_state
List cpp_stream_state(SEXP session);
RcppExport SEXP _rtranscribe_cpp_stream_state(SEXP sessionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_stream_state(session));
    return rcpp_result_gen;
END_RCPP
}
// cpp_stream_snapshot
List cpp_stream_snapshot(SEXP session);
RcppExport SEXP _rtranscribe_cpp_stream_snapshot(SEXP sessionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_stream_snapshot(session));
    return rcpp_result_gen;
END_RCPP
}
// cpp_whisper_chunk_traces
List cpp_whisper_chunk_traces(SEXP session);
RcppExport SEXP _rtranscribe_cpp_whisper_chunk_traces(SEXP sessionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_whisper_chunk_traces(session));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rtranscribe_cpp_status_string", (DL_FUNC) &_rtranscribe_cpp_status_string, 1},
    {"_rtranscribe_cpp_log_set", (DL_FUNC) &_rtranscribe_cpp_log_set, 2},
    {"_rtranscribe_cpp_log_drain", (DL_FUNC) &_rtranscribe_cpp_log_drain, 0},
    {"_rtranscribe_cpp_version", (DL_FUNC) &_rtranscribe_cpp_version, 0},
    {"_rtranscribe_cpp_init_backends_default", (DL_FUNC) &_rtranscribe_cpp_init_backends_default, 0},
    {"_rtranscribe_cpp_init_backends", (DL_FUNC) &_rtranscribe_cpp_init_backends, 1},
    {"_rtranscribe_cpp_backend_available", (DL_FUNC) &_rtranscribe_cpp_backend_available, 1},
    {"_rtranscribe_cpp_devices", (DL_FUNC) &_rtranscribe_cpp_devices, 0},
    {"_rtranscribe_cpp_model_load", (DL_FUNC) &_rtranscribe_cpp_model_load, 3},
    {"_rtranscribe_cpp_model_capabilities", (DL_FUNC) &_rtranscribe_cpp_model_capabilities, 1},
    {"_rtranscribe_cpp_model_supports", (DL_FUNC) &_rtranscribe_cpp_model_supports, 2},
    {"_rtranscribe_cpp_model_info", (DL_FUNC) &_rtranscribe_cpp_model_info, 1},
    {"_rtranscribe_cpp_model_meta", (DL_FUNC) &_rtranscribe_cpp_model_meta, 2},
    {"_rtranscribe_cpp_model_device", (DL_FUNC) &_rtranscribe_cpp_model_device, 1},
    {"_rtranscribe_cpp_model_accepts_ext_kind", (DL_FUNC) &_rtranscribe_cpp_model_accepts_ext_kind, 3},
    {"_rtranscribe_cpp_tokenize", (DL_FUNC) &_rtranscribe_cpp_tokenize, 2},
    {"_rtranscribe_cpp_session_init", (DL_FUNC) &_rtranscribe_cpp_session_init, 4},
    {"_rtranscribe_cpp_open", (DL_FUNC) &_rtranscribe_cpp_open, 6},
    {"_rtranscribe_cpp_session_limits", (DL_FUNC) &_rtranscribe_cpp_session_limits, 1},
    {"_rtranscribe_cpp_session_model", (DL_FUNC) &_rtranscribe_cpp_session_model, 1},
    {"_rtranscribe_cpp_run", (DL_FUNC) &_rtranscribe_cpp_run, 4},
    {"_rtranscribe_cpp_run_batch", (DL_FUNC) &_rtranscribe_cpp_run_batch, 4},
    {"_rtranscribe_cpp_stream_begin", (DL_FUNC) &_rtranscribe_cpp_stream_begin, 3},
    {"_rtranscribe_cpp_stream_feed", (DL_FUNC) &_rtranscribe_cpp_stream_feed, 3},
    {"_rtranscribe_cpp_stream_finalize", (DL_FUNC) &_rtranscribe_cpp_stream_finalize, 2},
    {"_rtranscribe_cpp_stream_reset", (DL_FUNC) &_rtranscribe_cpp_stream_reset, 1},
    {"_rtranscribe_cpp_stream_text", (DL_FUNC) &_rtranscribe_cpp_stream_text, 1},
    {"_rtranscribe_cpp_stream_state", (DL_FUNC) &_rtranscribe_cpp_stream_state, 1},
    {"_rtranscribe_cpp_stream_snapshot", (DL_FUNC) &_rtranscribe_cpp_stream_snapshot, 1},
    {"_rtranscribe_cpp_whisper_chunk_traces", (DL_FUNC) &_rtranscribe_cpp_whisper_chunk_traces, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rtranscribe(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
