# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_status_string <- function(status) {
    .Call(`_rtranscribe_cpp_status_string`, status)
}

cpp_log_set <- function(enabled, max_rank) {
    invisible(.Call(`_rtranscribe_cpp_log_set`, enabled, max_rank))
}

cpp_log_drain <- function() {
    .Call(`_rtranscribe_cpp_log_drain`)
}

cpp_version <- function() {
    .Call(`_rtranscribe_cpp_version`)
}

cpp_init_backends_default <- function() {
    .Call(`_rtranscribe_cpp_init_backends_default`)
}

cpp_init_backends <- function(dir) {
    .Call(`_rtranscribe_cpp_init_backends`, dir)
}

cpp_backend_available <- function(kind) {
    .Call(`_rtranscribe_cpp_backend_available`, kind)
}

cpp_devices <- function() {
    .Call(`_rtranscribe_cpp_devices`)
}

cpp_model_load <- function(path, backend, gpu_device) {
    .Call(`_rtranscribe_cpp_model_load`, path, backend, gpu_device)
}

cpp_model_capabilities <- function(model) {
    .Call(`_rtranscribe_cpp_model_capabilities`, model)
}

cpp_model_supports <- function(model, feature) {
    .Call(`_rtranscribe_cpp_model_supports`, model, feature)
}

cpp_model_info <- function(model) {
    .Call(`_rtranscribe_cpp_model_info`, model)
}

cpp_model_meta <- function(model, key) {
    .Call(`_rtranscribe_cpp_model_meta`, model, key)
}

cpp_model_device <- function(model) {
    .Call(`_rtranscribe_cpp_model_device`, model)
}

cpp_model_accepts_ext_kind <- function(model, slot, kind) {
    .Call(`_rtranscribe_cpp_model_accepts_ext_kind`, model, slot, kind)
}

cpp_tokenize <- function(model, text) {
    .Call(`_rtranscribe_cpp_tokenize`, model, text)
}

cpp_session_init <- function(model, n_threads, kv_type, n_ctx) {
    .Call(`_rtranscribe_cpp_session_init`, model, n_threads, kv_type, n_ctx)
}

cpp_open <- function(path, backend, gpu_device, n_threads, kv_type, n_ctx) {
    .Call(`_rtranscribe_cpp_open`, path, backend, gpu_device, n_threads, kv_type, n_ctx)
}

cpp_session_limits <- function(session) {
    .Call(`_rtranscribe_cpp_session_limits`, session)
}

cpp_session_model <- function(session) {
    .Call(`_rtranscribe_cpp_session_model`, session)
}

cpp_run <- function(session, pcm, opts, interruptible) {
    .Call(`_rtranscribe_cpp_run`, session, pcm, opts, interruptible)
}

cpp_run_batch <- function(session, pcms, opts, interruptible) {
    .Call(`_rtranscribe_cpp_run_batch`, session, pcms, opts, interruptible)
}

cpp_stream_begin <- function(session, run_opts, stream_opts) {
    invisible(.Call(`_rtranscribe_cpp_stream_begin`, session, run_opts, stream_opts))
}

cpp_stream_feed <- function(session, pcm, interruptible) {
    .Call(`_rtranscribe_cpp_stream_feed`, session, pcm, interruptible)
}

cpp_stream_finalize <- function(session, interruptible) {
    .Call(`_rtranscribe_cpp_stream_finalize`, session, interruptible)
}

cpp_stream_reset <- function(session) {
    invisible(.Call(`_rtranscribe_cpp_stream_reset`, session))
}

cpp_stream_text <- function(session) {
    .Call(`_rtranscribe_cpp_stream_text`, session)
}

cpp_stream_state <- function(session) {
    .Call(`_rtranscribe_cpp_stream_state`, session)
}

cpp_stream_snapshot <- function(session) {
    .Call(`_rtranscribe_cpp_stream_snapshot`, session)
}

cpp_whisper_chunk_traces <- function(session) {
    .Call(`_rtranscribe_cpp_whisper_chunk_traces`, session)
}

